### ISSUE TITLE
You are not allowed to access the given folder

### ISSUE THREAD

**Issue by kersten** [andersundsehr/aus_driver_amazon_s3#18]
Hi,

just found out, when saving an form I get exception `1375955684` saying: "You are not allowed to access the given folder".

This is the function involved in that error, may you have a look at it?

https://github.com/TYPO3/TYPO3.CMS/blob/b49e638283e682e0808f49c09210ba3f302b7f61/typo3/sysext/core/Classes/Resource/ResourceStorage.php#L756

```php
    protected function assureFolderReadPermission(Folder $folder = null)
    {
        if (!$this->checkFolderActionPermission('read', $folder)) {
            if ($folder === null) {
                throw new Exception\InsufficientFolderAccessPermissionsException(
                    'You are not allowed to read folders',
                    1430657869
                );
            } else {
                throw new Exception\InsufficientFolderAccessPermissionsException(
                    'You are not allowed to access the given folder: "' . $folder->getName() . '"',
                    1375955684
                );
            }
        }
    }
```

**Comment by Lagerregal** [comment]
Hi,
thanks for your report. How can I reproduce this issue? Which "form" was mentioned? Which TYPO3 version?

**Comment by kersten** [comment]
Sure. I use ext:form from Typo3 8.6. Then I set the config for the ext in yaml:

```
TYPO3:
  CMS:
    Form:
      persistenceManager:
        allowedFileMounts:
          11: 2:/
```

After that i moved already created forms to S3. Then I tried to edit the form and when I click save the error comes up.

**Comment by dni** [comment]
i cant reproduce this issue, im using this yaml, and never had a issue with it, try looking if your storage really has the ID 2.

And then only transfer the forms via the duplicate function in tx_form, where in step1 you then can select the storage. i also had errors with tx_form when i manually moved the configs

```yaml
 TYPO3:                                                                                                                                           
   CMS:                                                                                                                                           
     Form:                                                                                                                                        
       persistenceManager:                                                                                                                        
         allowedFileMounts:                                                                                                                       
           20: 2:/forms/  
```
